### ISSUE TITLE
Unknown method getTranslationsByFid

### ISSUE THREAD

**Issue by Samson1964** [Craffft/contao-photoalbums2#140] opened 2018-08-05 14:13 UTC
Unter Contao 4.5.10 erscheint beim Aufruf eines Albums im Backend oder beim Anlegen eines Albums die obige Fehlermeldung.
In der prod-Logdatei steht: app.CRITICAL: An exception occurred. {"exception":"[object] (Exception(code: 0): Unknown method getTranslationsByFid at /xxx/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php:992)"} [] 

Stacktrace im Dev-Modus:
Exception:
Unknown method getTranslationsByFid

  at vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php:992
  at Contao\Model::__callStatic('getTranslationsByFid', array('300'))
     (vendor/craffft/translation-fields-bundle/src/Widget/TranslationTextField.php:101)
  at Craffft\TranslationFieldsBundle\Widget\TranslationTextField->generate()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Widget.php:676)
  at Contao\Widget->generateWithError(true)
     (vendor/contao/core-bundle/src/Resources/contao/templates/backend/be_widget.html5:3)
  at include('/xxx/vendor/contao/core-bundle/src/Resources/contao/templates/backend/be_widget.html5')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateInheritance.php:96)
  at Contao\Widget->inherit()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Widget.php:625)
  at Contao\Widget->parse()
     (vendor/contao/core-bundle/src/Resources/contao/classes/DataContainer.php:670)
  at Contao\DataContainer->row('{title_legend},title,alias,author;{date_legend},startdate,enddate;{images_legend},images,imageSortType,previewImageType,previewImage;{info_legend},event,place,photographer,description;{protected_legend},protected;{expert_legend:hide},cssClass,noComments;{published_legend},published,start,stop')
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:1971)
  at Contao\DC_Table->edit()
     (vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:620)
  at Contao\Backend->getBackendModule('photoalbums2', null)
     (vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:131)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:50)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/app_dev.php:67)
 

Wenn ich die Zeile 101 in TranslationTextField.php ändere auf  $this->varValue = '' ändere kommt ein Fehler Could not find template "be_tinyFlash"

**Comment by iCodr8** [comment] 2019-07-12 21:20
Duplicate of https://github.com/Craffft/contao-photoalbums2/issues/137

**Closed by iCodr8** 2019-07-12 21:20 UTC
Labels: defect
